[package]
name = "hsr-codegen"
version = "0.1.0"
authors = ["jesskfulwood <jesskfulwood@gmail.com>"]
edition = "2018"

[dependencies]
derive_more = "0.15.0"
failure = "0.1.5"
heck = "0.3.1"
http = "0.1.17"
openapiv3 = "0.2.0"
proc-macro2 = "0.4.30"
quote = "0.6.12"
regex = "1.1.7"
log = "0.4.6"
rustfmt-nightly = "1.3.0"
serde_yaml = "0.8.9"
syn = "0.15.36"

[dev-dependencies]
diff = "0.1.11"
