[package]
name = "hsr-codegen"
version = "0.1.0"
authors = ["jesskfulwood <jesskfulwood@gmail.com>"]
edition = "2018"

[dependencies]
derive_more = "0.15.0"
failure = "0.1.5"
heck = "0.3.1"
http = "0.1.17"
openapiv3 = "0.2.0"
proc-macro2 = "0.4.30"
quote = "0.6.13"
regex = "1.1.9"
log = "0.4.7"
rustfmt-nightly = "1.3.2"
serde_yaml = "0.8.9"
structopt = "0.2.18"
syn = "0.15.39"
derive_deref = "1.1.0"
either = "1.5.2"

[dev-dependencies]
diff = "0.1.11"
env_logger = "0.6.2"
tempdir = "0.3.7"
yansi = "0.5.0"
