openapi: "3.0.0"
info:
  version: 1.0.0
  title: Benchmark
servers:
  - url: http://localhost:8000

paths:
  /:
    get:
      operationId: basicGet
      responses:
        '200':
          description: Simple get

    post:
      operationId: basicPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payload'
      responses:
        '200':
          description: Simple post with payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Payload"

components:
  schemas:
    Payload:
      required:
        - key1
        - key2
      properties:
        key1:
          type: number
        key2:
          type: string
