[package]
name = "bench"
version = "0.0.0"
authors = ["Alex Whitney <adwhit@fastmail.com>"]
edition = "2021"

[build-dependencies]
hsr-codegen = { path = "../../hsr-codegen" }

[dependencies]
hsr = { path = "../../hsr" }
serde = "1.0.147"
actix-rt = "2.7.0"
