[package]
name = "petstore"
version = "0.1.0"
authors = ["jesskfulwood <jesskfulwood@gmail.com>"]
edition = "2018"

[build-dependencies]
hsr-codegen = { path = "../../hsr-codegen" }

[[bin]]
name = "petstore-server"
path = "src/bin/server.rs"

[[bin]]
name = "petstore-client"
path = "src/bin/client.rs"

[dependencies]
hsr = { path = "../../hsr" }
serde = { version = "1.0.98", features = ['derive'] }
regex = "1.2.0"
rand = "0.7.0"
env_logger = "0.6.2"

[features]
rustfmt = ["hsr-codegen/rustfmt"]
