[package]
name = "quickstart"
version = "0.1.0"
authors = ["jesskfulwood <jesskfulwood@gmail.com>"]
edition = "2018"

[build-dependencies]
hsr-codegen = { path = "../../hsr-codegen", features = ["rustfmt"] }

[dependencies]
hsr = { path = "../../hsr" }
serde = "1.0.104"
actix-rt = "1.0.0"
env_logger = "0.7.1"
