openapi: "3.0.0"
info:
  version: 1.0.0
  title: Quickstart
servers:
  - url: http://localhost:8000
paths:
  /{name}:
    get:
      summary: Quickstart
      operationId: greet
      parameters:
        - name: name
          in: path
          required: true
          description: User name
          schema:
            type: string
      responses:
        '200':
          description: Hello
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hello"
components:
  schemas:
    Hello:
      required:
        - name
        - greeting
      properties:
        name:
          type: string
        greeting:
          type: string
